import { Model } from '@nozbe/watermelondb';
import { field, text } from '@nozbe/watermelondb/decorators';
import { SyncStatus } from '../../../constants/syncConstants'; // REQ-14-003, REQ-14-004

/**
 * REQ-14-003: Generation of local UUIDs for offline creations. (Handled by OfflineIdGenerator, id field stores it)
 * REQ-14-004: Detection and resolution of data conflicts. (Fields support this)
 * REQ-14-006: Bi-directional data synchronization with the backend via the API Gateway. (Fields support this)
 */
export class BaseModel extends Model {
  // The `id` field is a standard WatermelonDB field.
  // Per SDS, it will store a UUID generated by OfflineIdGenerator.ts.
  // It is defined in the schema.ts for each table as: { name: 'id', type: 'string', isIndexed: true }

  @text('remote_id') remoteId?: string | null;
  @text('sync_status') syncStatus!: SyncStatus;
  @field('last_modified_locally_at') lastModifiedLocallyAt!: number; // Timestamp
  @field('server_last_modified_at') serverLastModifiedAt?: number | null; // Timestamp
  @field('created_at') createdAt!: number; // Timestamp for when the record was created (locally or synced from server)
  @field('updated_at') updatedAt!: number; // Timestamp for when the record was last updated (locally or synced from server)

  // Example of how a model extending BaseModel might update common fields:
  async setSynced(remoteIdFromServer: string, serverTimestamp: number) {
    await this.update(record => {
      const self = record as BaseModel;
      self.remoteId = remoteIdFromServer;
      self.syncStatus = SyncStatus.SYNCED;
      self.serverLastModifiedAt = serverTimestamp;
      self.updatedAt = serverTimestamp; // Or keep local updatedAt if server doesn't override
    });
  }

  async setRequiresUpdate() {
    // If already PENDING_CREATE, keep it that way. Otherwise PENDING_UPDATE.
    if (this.syncStatus !== SyncStatus.PENDING_CREATE) {
        await this.update(record => {
            const self = record as BaseModel;
            self.syncStatus = SyncStatus.PENDING_UPDATE;
            self.lastModifiedLocallyAt = Date.now();
            self.updatedAt = self.lastModifiedLocallyAt;
        });
    } else {
        // If it's a new record, just update timestamps
        await this.update(record => {
            const self = record as BaseModel;
            self.lastModifiedLocallyAt = Date.now();
            self.updatedAt = self.lastModifiedLocallyAt;
        });
    }
  }

  async setConflict() {
    await this.update(record => {
      const self = record as BaseModel;
      self.syncStatus = SyncStatus.CONFLICT;
      self.updatedAt = Date.now(); // Local timestamp update
    });
  }

  async setRequiresUniquenessValidation() {
    await this.update(record => {
      const self = record as BaseModel;
      self.syncStatus = SyncStatus.REQUIRES_UNIQUENESS_VALIDATION;
      self.updatedAt = Date.now();
    });
  }
}