import { Model, Q } from '@nozbe/watermelondb';
import { field, text, children, readonly, date, writer } from '@nozbe/watermelondb/decorators';
import { Associations } from '@nozbe/watermelondb/Model';
import { TableName } from '../TableName';
import LandRecord from './LandRecord'; // eslint-disable-line import/no-cycle
import Address from './Address'; // Assuming Address model will be created
// import { generateUUID } from '../../utils/uuidGenerator'; // Assuming a UUID generator utility

export default class Farmer extends Model {
  static table = TableName.FARMERS;

  static associations: Associations = {
    [TableName.LAND_RECORDS]: { type: 'has_many', foreignKey: 'farmer_id' },
    [TableName.ADDRESSES]: { type: 'has_many', foreignKey: 'farmer_id' }, // Assuming Address model will exist
  };

  // Base Model Fields (as per SDS for BaseModel)
  @readonly @text('id') id!: string;
  @text('remote_id') remoteId?: string | null;
  @text('sync_status') syncStatus!: string; // e.g., 'PENDING_CREATE', 'SYNCED', 'PENDING_UPDATE', 'CONFLICT'
  @date('last_modified_locally_at') lastModifiedLocallyAt!: number;
  @date('server_last_modified_at') serverLastModifiedAt?: number | null;
  @readonly @date('created_at') createdAt!: number;
  @date('updated_at') updatedAt!: number;

  // Farmer Specific Fields (subset for mobile offline capture)
  @text('first_name') firstName!: string;
  @text('middle_name') middleName?: string | null;
  @text('last_name') lastName!: string;
  @date('date_of_birth') dateOfBirth!: number; // Store as timestamp
  @field('gender_id') genderId?: number | null; // Assuming gender is a lookup ID
  @text('primary_phone') primaryPhone!: string;
  @text('secondary_phone') secondaryPhone?: string | null;
  @text('email') email?: string | null;
  @text('national_id_number') nationalIdNumber?: string | null;
  @text('national_id_type') nationalIdType?: string | null; // e.g., 'PASSPORT', 'NATIONAL_ID_CARD'
  @field('family_size') familySize?: number | null;
  @field('farming_experience_years') farmingExperienceYears?: number | null;
  @field('preferred_language_id') preferredLanguageId?: number | null; // Assuming language is a lookup ID
  @field('status_id') statusId?: number | null; // Domain-specific status, e.g., 'ACTIVE', 'PENDING_APPROVAL'

  @children(TableName.LAND_RECORDS) landRecords!: Q.Query<LandRecord>;
  // @children(TableName.ADDRESSES) addresses!: Q.Query<Address>; // Uncomment when Address model is available

  // Example of a writer method for creation - WatermelonDB handles ID generation by default
  @writer async createFarmer(data: {
    firstName: string;
    lastName: string;
    primaryPhone: string;
    dateOfBirth: number;
    // id: string; // id will be auto-generated by WatermelonDB
    syncStatus: string;
    // other fields...
  }) {
    const now = Date.now();
    return this.collection.create<Farmer>(farmer => {
      // farmer.id = data.id; // Not needed if WatermelonDB auto-generates
      farmer.firstName = data.firstName;
      farmer.lastName = data.lastName;
      farmer.primaryPhone = data.primaryPhone;
      farmer.dateOfBirth = data.dateOfBirth;
      farmer.syncStatus = data.syncStatus;
      farmer.lastModifiedLocallyAt = now;
      farmer.createdAt = now;
      farmer.updatedAt = now;
      // map other fields from data to farmer model
    });
  }

  @writer async updateFarmer(data: Partial<Omit<Farmer, keyof Model | 'id' | 'createdAt'>>) {
    const now = Date.now();
    return this.update(farmer => {
      Object.assign(farmer, data);
      farmer.updatedAt = now;
      farmer.lastModifiedLocallyAt = now;
    });
  }

  @writer async markAsDeleted() {
    return this.update(farmer => {
        farmer.syncStatus = 'PENDING_DELETE'; // Or however you mark for deletion
        farmer.updatedAt = Date.now();
        farmer.lastModifiedLocallyAt = Date.now();
    });
    // For actual deletion:
    // return super.markAsDeleted(); // marks as deleted, then syncs deletion
    // await super.destroyPermanently(); // if you want to delete from local db immediately
  }
}