import { Model } from '@nozbe/watermelondb';
import { field, text, readonly, date, writer } from '@nozbe/watermelondb/decorators';
import { TableName } from '../TableName';
// import { generateUUID } from '../../utils/uuidGenerator'; // Assuming a UUID generator utility

export enum SyncOperationType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export default class SyncQueueItem extends Model {
  static table = TableName.SYNC_QUEUE_ITEMS;

  @readonly @text('id') id!: string; // Local UUID for the queue item itself

  @text('entity_table_name') entityTableName!: string; // e.g., 'farmers', 'land_records'
  @text('entity_id') entityId!: string; // Local UUID of the actual data record (Farmer ID, LandRecord ID)
  @text('operation_type') operationType!: SyncOperationType; // 'CREATE', 'UPDATE', 'DELETE'
  
  @text('payload') payload?: string | null; // JSON string of the data for CREATE/UPDATE
                                          // For DELETE, this might be null or contain just the ID

  @field('attempt_count') attemptCount!: number;
  @date('last_attempt_at') lastAttemptAt?: number | null;
  @text('error_message') errorMessage?: string | null; // Last error message if sync failed

  @readonly @date('created_at') createdAt!: number; // Timestamp when queue item was created


  @writer async createSyncQueueItem(data: {
    // id: string; // Auto-generated by WatermelonDB
    entityTableName: string;
    entityId: string;
    operationType: SyncOperationType;
    payload?: string | null;
  }) {
    const now = Date.now();
    return this.collection.create<SyncQueueItem>(item => {
    //   item.id = data.id;
      item.entityTableName = data.entityTableName;
      item.entityId = data.entityId;
      item.operationType = data.operationType;
      item.payload = data.payload ?? null;
      item.attemptCount = 0;
      item.createdAt = now;
    });
  }

  @writer async recordSyncAttempt(success: boolean, error?: string) {
    return this.update(item => {
      item.attemptCount += 1;
      item.lastAttemptAt = Date.now();
      if (!success && error) {
        item.errorMessage = error;
      } else if (success) {
        item.errorMessage = null; 
      }
    });
  }

  // SyncQueueItems are typically deleted once successfully processed, not 'updated' in other ways.
  @writer async deleteQueueItem() {
    return super.destroyPermanently();
  }
}