package com.thesss.platform.land.domain.model;

import lombok.Value;
import java.time.Instant;

/**
 * Value Object embedding audit information.
 * REQ-2-018
 */
@Value // Lombok annotation for immutable class
public class AuditInfo {
    String createdBy;
    Instant createdDate;
    String lastModifiedBy;
    Instant lastModifiedDate;

    // Constructor is generated by @Value.
    // This VO is typically populated by JPA Auditing mechanisms.
}